name: 'Github_Action_Monitor_Webpage'
description: 'Monitor Webpage defined in config, compare with previous information, output difference.'

inputs:
  prevInfoPath:
    description: Path of previous information JSON.
    required: true
    default: '../prevInfo.json'

outputs:
  changed:
    description: Flag of change or not.
      #'true' or 'false'.
  title:
    description: Title of difference.
  pureText:
    description: Pure text of difference.
  markdownText:
    description: Markdown format of difference.

runs:
  using: 'node12'
  main: 'index.js'
